import './globals.css'
import { Header } from "../components/header";

import type { Metadata } from 'next'

import { Nunito } from 'next/font/google'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={nunito.className}>
        <Header />

          <main className="bg-page-gradient pt-navigation-height">
            {children}
          </main>


        </div>

      </body>
    </html>
  )
}
